agro_intelligence_coop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 13.222.170.228
      user: agro_user
      password: agro_password
      port: 5432
      dbname: agro_db
      schema: dev
      threads: 4